### ISSUE TITLE
Flashcards

### ISSUE THREAD

**Issue by zhemepatis** [OvidijusStankaitis/PSI_Project#30]
What if we added a feature where user could create flashcards and as an answer of created flashcard they could mark something in one of the files? I think it would make creation of flashcards more convenient.

**Comment by OvidijusStankaitis** [comment]
There are notes already. Also we don't have the time to integrate the marking of pdfs. Not all pdfs are text based. Some are scanned pdfs. They essentially are a picture in a form of a pdf. That would take more time than we have
