### ISSUE TITLE
Change model Ids from GUID string to simple integers

### ISSUE THREAD

**Issue by zhemepatis** [OvidijusStankaitis/PSI_Project#36]
It was advised during one of the lectures. GUIDs might raise some issues later on.

**Comment by OvidijusStankaitis** [comment]
No worries on the GUIDs. GUIDs have 2^122 combinations, and there are duplicates only when there is a bug in the program (as much as I read the bugs are very hard to produce. The most likely scenario of a duplication is if we would have 2^122 elements in the database) . Also it would take away time to restructure the project, and we don't have enough time left
